services:
  - type: web
    name: younes-portfolio-api
    env: python
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn portfolio_backend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "younes-portfolio-api.onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://younes-sadir.vercel.app,https://frontend-six-beryl-25.vercel.app"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://younes-sadir.vercel.app,https://frontend-six-beryl-25.vercel.app,https://younes-portfolio-api.onrender.com"
      - key: GMAIL_USER
        value: "younesadir@gmail.com"
      - key: GMAIL_PASSWORD
        value: "txjklivxzezcbunu"
      - key: NOTIFICATION_EMAIL
        value: "younesadir@gmail.com"
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString

databases:
  - name: portfolio-db
    plan: free
    region: frankfurt
